apiVersion: v1
kind: ConfigMap
metadata:
  name: cinemaabyss-config
  namespace: cinemaabyss
data:
  # Database configuration
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "cinemaabyss"
  DB_USER: "postgres"

  # Service URLs
  MONOLITH_PROTOCOL: "http"
  MONOLITH_HOST: "monolith-service"
  MONOLITH_PORT: "8080"
  MOVIES_SERVICE_PROTOCOL: "http"
  MOVIES_SERVICE_HOST: "movies-service"
  MOVIES_SERVICE_PORT: "8081"
  EVENTS_SERVICE_PROTOCOL: "http"
  EVENTS_SERVICE_HOST: "events-service"
  EVENTS_SERVICE_PORT: "8082"
  
  # Strangler Fig configuration
  GRADUAL_MIGRATION: "true"
  MOVIES_MIGRATION_PERCENT: "100"
