apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-service
  namespace: cinemaabyss
  labels:
    app: monolith-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: monolith-service
    spec:
      containers:
      - name: monolith-service
        image:  ghcr.io/timberk/cinemaabyss/monolith:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DB_CONNECTION_STRING
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
        envFrom:
        - configMapRef:
            name: cinemaabyss-config
        - secretRef:
            name: cinemaabyss-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /api/users
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/users
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: monolith-service
  namespace: cinemaabyss
spec:
  selector:
    app: monolith-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP